insert into public.deals (
  id,
  owner_id,
  business_type,
  status,
  business_name,
  logo_url,
  image_url,
  title,
  description,
  offer_text,
  website_url,
  product_url,
  has_timer,
  distance,
  lat,
  lng,
  created_at,
  expires_at,
  max_claims,
  current_claims,
  claim_count,
  category
)
values
  (
    'test-online-1',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    'Wireless Earbuds Test Drop',
    'Test online deal for verifying that the hosted LiveDrop app reads Online Drops from Supabase.',
    '25% OFF',
    'https://amzn.to/4rJ4KtO',
    'https://amzn.to/4rJ4KtO',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '10 minutes',
    timezone('utc', now()) + interval '2 hours',
    999,
    84,
    84,
    'Tech'
  ),
  (
    'test-online-2',
    null,
    'online',
    'active',
    'Pixel Forge',
    null,
    'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
    'Mechanical Keyboard Weekend Drop',
    'A seeded test deal to confirm shared database-backed Online Drops are rendering in production.',
    '40% OFF',
    'https://example.com/pixel-forge/keyboards',
    'https://example.com/pixel-forge/keyboards',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '18 minutes',
    timezone('utc', now()) + interval '95 minutes',
    999,
    126,
    126,
    'Tech'
  ),
  (
    'test-online-3',
    null,
    'online',
    'active',
    'Cloud Kicks',
    null,
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    'Sneaker Flash Sale Test',
    'Shared test card for validating Fashion online deals from the Supabase deals table.',
    'DEAL',
    'https://example.com/cloud-kicks/weekend-drop',
    'https://example.com/cloud-kicks/weekend-drop',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '150 minutes',
    999,
    42,
    42,
    'Fashion'
  ),
  (
    'test-online-4',
    null,
    'online',
    'active',
    'Quest Crate',
    null,
    'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=900&q=80',
    'Indie Bundle Test Event',
    'Gaming test drop for confirming category filtering and shared production rendering.',
    'LIMITED',
    'https://example.com/quest-crate/indie-rpg-bundle',
    'https://example.com/quest-crate/indie-rpg-bundle',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '32 minutes',
    timezone('utc', now()) + interval '70 minutes',
    999,
    61,
    61,
    'Gaming'
  ),
  (
    'test-online-5',
    null,
    'online',
    'active',
    'Northern Nest',
    null,
    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    'Home Essentials Test Drop',
    'Home category test deal for checking that the hosted app is reading active online deals from Supabase.',
    '30% OFF',
    'https://example.com/northern-nest/linen-event',
    'https://example.com/northern-nest/linen-event',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '14 minutes',
    timezone('utc', now()) + interval '3 hours',
    999,
    27,
    27,
    'Home'
  )
on conflict (id) do update
set
  status = excluded.status,
  business_name = excluded.business_name,
  image_url = excluded.image_url,
  title = excluded.title,
  description = excluded.description,
  offer_text = excluded.offer_text,
  website_url = excluded.website_url,
  product_url = excluded.product_url,
  has_timer = excluded.has_timer,
  created_at = excluded.created_at,
  expires_at = excluded.expires_at,
  max_claims = excluded.max_claims,
  current_claims = excluded.current_claims,
  claim_count = excluded.claim_count,
  category = excluded.category;
