insert into public.deals (
  id,
  owner_id,
  business_type,
  status,
  business_name,
  logo_url,
  image_url,
  title,
  description,
  offer_text,
  website_url,
  product_url,
  has_timer,
  distance,
  lat,
  lng,
  created_at,
  expires_at,
  max_claims,
  current_claims,
  claim_count,
  category
)
values
  (
    'online-seed-0',
    null,
    'online',
    'active',
    'Amazon Fire TV',
    null,
    null,
    'Amazon Fire TV Stick 4K Plus (Newest Model) with AI-Powered Fire TV Search and Wi-Fi 6',
    'Streaming stick deal with 4K support, AI-powered Fire TV search, and faster Wi-Fi 6 playback.',
    '$49.99 -> $29.99',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B0F7Z4QZTT',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1 minute',
    timezone('utc', now()) + interval '2 hours',
    999,
    126,
    126,
    'Tech'
  ),
  (
    'online-seed-0b',
    null,
    'online',
    'active',
    'D-Link',
    null,
    null,
    'D-Link Pro Series Compact Full HD Pan & Tilt Wi-Fi Camera',
    'Compact indoor security camera with pan-and-tilt coverage, Full HD video, and smart home monitoring.',
    '$79.99 -> $29.99',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B00PS13QSO',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1.5 minutes',
    timezone('utc', now()) + interval '1.5 hours',
    999,
    92,
    92,
    'Home'
  ),
  (
    'online-seed-1',
    null,
    'online',
    'active',
    'Orgain',
    null,
    null,
    'Orgain Organic Wonder Gut Fiber Supplement Powder, Strawberry Lemonade',
    'Digestive fiber powder deal with a steep markdown and frequent coupon-style stacking on Amazon.',
    '$29.99 -> $9.73',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B0CXV56J4G',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '2.5 hours',
    999,
    51,
    51,
    'Home'
  ),
  (
    'online-seed-2',
    null,
    'online',
    'active',
    'KK Lights',
    null,
    null,
    'Cordless Table Lamp Rechargeable Gold, 2-Pack 5000mAh Battery Lamps',
    'Rechargeable cordless lamp set with a gold finish and promo-style pricing for bedside or patio setups.',
    'PROMO PRICE ~ $14.99',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B0DJYFJGQW',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '6 minutes',
    timezone('utc', now()) + interval '1.5 hours',
    999,
    38,
    38,
    'Home'
  ),
  (
    'online-seed-home-1',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/71LbDwKqAvL._AC_SL1500_.jpg',
    'GRLEAF 70" Sofa Table with Built-in Power Strip (2 AC Outlets & 2 USB Ports) - Rustic Brown',
    'Long narrow sofa table with built-in outlets and USB ports, made for behind-the-couch setups and compact home-office spaces.',
    'HOME DROP',
    'https://www.amazon.com',
    'https://www.amazon.com/GRLEAF-Narrow-Console-Built-Outlets/dp/B0DQXZ4J2Y',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '1.8 hours',
    999,
    54,
    54,
    'Home'
  ),
  (
    'online-seed-home-2',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/71xgtQ+NvNL._AC_SL1500_.jpg',
    'JESONVID Solid Wood Console Table with 2 Drawers - Blue',
    'Solid wood console table with dual drawers and layered storage shelving for entryway, living room, or office use.',
    'LIMITED HOME DEAL',
    'https://www.amazon.com',
    'https://www.amazon.com/Console-Drawers-Multilayer-Entryway-Office-Blue/dp/B0BDFLV9SZ',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '3 minutes',
    timezone('utc', now()) + interval '2 hours',
    999,
    41,
    41,
    'Home'
  ),
  (
    'online-seed-home-3',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/61I4-1dK6EL._AC_SL1500_.jpg',
    'Modern Upholstered Accent Chair',
    'Modern fabric armchair with solid wood legs and a compact accent-chair silhouette for bedroom, balcony, or living room corners.',
    'FEATURED HOME FIND',
    'https://www.amazon.com',
    'https://www.amazon.com/NABEIM-Upholstered-Armchair-Practical-Fashionable/dp/B09C1BWF1D',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '4 minutes',
    timezone('utc', now()) + interval '2.3 hours',
    999,
    36,
    36,
    'Home'
  ),
  (
    'online-seed-home-4',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/51WEji-E7PL._AC_SL1200_.jpg',
    'DORTALA Nightstand Wooden 2-Tier Couch Sofa Side Table with Drawer',
    'Compact gray side table with drawer and lower shelf storage, built for bedside or living-room corners.',
    'FLASH HOME SALE',
    'https://m.media-amazon.com/images/I/51WEji-E7PL._AC_SL1200_.jpg',
    'https://www.amazon.com/DORTALA-Nightstand-Storage-Mufti-Functional-Furniture/dp/B08L9C6332',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '1.7 hours',
    999,
    29,
    29,
    'Home'
  ),
  (
    'online-seed-home-5',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/91PnpJzpFvL._AC_SL1500_.jpg',
    'Alaterre Furniture Fluted Solid Wood Console Table - Light Oak',
    'Modern fluted entryway console table with a lower shelf and a clean light-oak finish for hallway or couch-behind styling.',
    'JUST DROPPED',
    'https://www.amazon.com',
    'https://www.amazon.com/Alaterre-Furniture-Fluted-Solid-Console/dp/B0GGTP979F',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '6 minutes',
    timezone('utc', now()) + interval '2.2 hours',
    999,
    48,
    48,
    'Home'
  ),
  (
    'online-seed-4b',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    'Amazon Essentials Men\'s Tee Deal Drop',
    'A fresh Amazon Essentials men\'s t-shirt search drop with affordable basics, multipacks, and everyday wardrobe picks ready to browse now.',
    'FASHION DEAL',
    'https://www.amazon.com',
    'https://www.amazon.com/s?k=amazon+essentials+mens+t+shirt',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '45 seconds',
    timezone('utc', now()) + interval '2 hours',
    999,
    68,
    68,
    'Fashion'
  ),
  (
    'online-seed-4c',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    'Cheap Hoodies for Men Flash Sale',
    'Browse budget-friendly men\'s hoodies, fleece layers, and everyday cold-weather essentials in this Amazon fashion search deal.',
    'FLASH SALE',
    'https://www.amazon.com',
    'https://www.amazon.com/s?k=cheap+hoodies+men',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1 minute',
    timezone('utc', now()) + interval '1.8 hours',
    999,
    91,
    91,
    'Fashion'
  ),
  (
    'online-seed-4d',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
    'Gildan Hoodie Everyday Deal',
    'A Gildan hoodie search page packed with casual fleece options, everyday layers, and easy-price wardrobe staples.',
    'DEAL',
    'https://www.amazon.com',
    'https://www.amazon.com/s?k=gildan+hoodie',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1.2 minutes',
    timezone('utc', now()) + interval '1.5 hours',
    999,
    57,
    57,
    'Fashion'
  ),
  (
    'online-seed-4e',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
    'Amazon Essentials Tank Top Multi-Pack Save',
    'A warm-weather basics search featuring Amazon Essentials tank tops, loungewear staples, and simple everyday layering pieces.',
    'LIMITED DEAL',
    'https://www.amazon.com',
    'https://www.amazon.com/s?k=amazon+essentials+tank+top',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1.5 minutes',
    timezone('utc', now()) + interval '2.3 hours',
    999,
    42,
    42,
    'Fashion'
  ),
  (
    'online-seed-4f',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
    'Men\'s Fashion Deals Roundup',
    'An Amazon men\'s fashion search page with mixed apparel deals, wardrobe basics, and current markdowns gathered into one browsing destination.',
    'TRENDING DEALS',
    'https://www.amazon.com',
    'https://www.amazon.com/s?k=mens+fashion+deals',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1.7 minutes',
    timezone('utc', now()) + interval '2 hours',
    999,
    133,
    133,
    'Fashion'
  ),
  (
    'online-seed-31',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    'Beats Studio Pro Noise-Canceling Headphones',
    'Premium over-ear wireless headphones with personalized spatial audio and all-day battery are on a limited Amazon drop right now.',
    '18% OFF',
    'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
    'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '12 minutes',
    timezone('utc', now()) + interval '2 hours 15 minutes',
    999,
    167,
    167,
    'Tech'
  ),
  (
    'online-seed-32',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
    'Smart Desk Lamp Deal Drop',
    'A compact LED desk lamp with adjustable brightness and a clean home-office look is moving fast in today’s Amazon event.',
    'DEAL',
    'https://amzn.to/XXXX',
    'https://amzn.to/XXXX',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '22 minutes',
    timezone('utc', now()) + interval '1.5 hours',
    999,
    121,
    121,
    'Home'
  ),
  (
    'online-seed-33',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    'Everyday Sneaker Flash Markdown',
    'Lightweight casual sneakers are part of a quick online apparel markdown with fresh sizes still in stock.',
    '20% OFF',
    'https://amzn.to/XXXX',
    'https://amzn.to/XXXX',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '8 minutes',
    timezone('utc', now()) + interval '2.5 hours',
    999,
    44,
    44,
    'Fashion'
  ),
  (
    'online-seed-35',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=900&q=80',
    'Portable Charger Quick Save',
    'A travel-friendly battery pack with USB-C fast charging is part of a fresh mobile-tech deal drop today.',
    '25% OFF',
    'https://amzn.to/XXXX',
    'https://amzn.to/XXXX',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '18 minutes',
    timezone('utc', now()) + interval '1.2 hours',
    999,
    152,
    152,
    'Tech'
  ),
  (
    'momcozy-kleanpal-pro',
    null,
    'online',
    'active',
    'Momcozy',
    null,
    'https://m.media-amazon.com/images/I/51bYxBVtzSL._SY355_.jpg',
    'Momcozy KleanPal Pro Baby Bottle Washer',
    'All-in-One Cleaning Machine for Bottles, Pump Parts & Baby Essentials - Time-Saving & Effortless Care. Powerful cleaning with steam sterilization and comprehensive drying.',
    '33% OFF - $239.99',
    'https://www.amazon.com',
    'https://amzn.to/4bNgyoT',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '24 hours',
    50,
    12,
    12,
    'Home'
  ),
  (
    'samsung-watch-band-ynitec',
    null,
    'online',
    'active',
    'Ynitec',
    null,
    'https://m.media-amazon.com/images/I/61Z09Ia2gOL._AC_SY395_.jpg',
    'Sport Bands Compatible with Samsung Galaxy Watch 7 6 5 4 Band 40mm 44mm',
    'No Gap Soft Silicone Strap for Smart Watch S 7 6 5 4 FE, 20mm Wristbands for GalaxyWatch. Features gapless connection technology, durable stainless steel buckle, breathable and sweat-resistant material.',
    '$5.99 (30% OFF)',
    'https://www.amazon.com',
    'https://amzn.to/4bOaJYr',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '12 hours',
    100,
    87,
    87,
    'Tech'
  ),
  (
    'purecozy-checkered-rug',
    null,
    'online',
    'active',
    'PureCozy',
    null,
    'https://m.media-amazon.com/images/I/81SEI2WN9pL._AC_SY450_.jpg',
    'Checkered Runner Rug 2x6 for Bedroom, Brown Modern Shag Rug Super Soft Long Carpet Washable Fluffy Rugs for Living Room Bedside Sofa Home Dorm Decor Aesthetic',
    'Plush Modern Rug: PureCozy fuzzy rug has a long and plush pile, creating a cozy and luxurious feel for your home. Perfect for modern home decor, it blends seamlessly into living rooms, bedrooms. Eco-friendly packaging, rug may look flat at first—just lay it flat for 48h to regain its full thickness and fluffiness.',
    '$14.39 (30% OFF)',
    'https://www.amazon.com',
    'https://amzn.to/4t0cxnS',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1 minute',
    timezone('utc', now()) + interval '24 hours',
    50,
    5,
    5,
    'Home'
  ),
  (
    'online-seed-36',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/61A5VWc9rBL._AC_SL1200_.jpg',
    'Smart Home Essential: Amazon Product (B0GHRPJ8SY)',
    'Amazon-listed smart home device optimized for modern kitchen and home use, now on a trending discount via affiliate deal.',
    '19% OFF',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B0GHRPJ8SY?ref=t_ac_view_request_product_title&th=1',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '4 hours',
    999,
    174,
    174,
    'Home'
  ),
  (
    'online-seed-37',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://m.media-amazon.com/images/I/61VjXKxzD7L._AC_SL1200_.jpg',
    'Trending Home Pick: Smart Kitchen Essential (B0GDFY12X5)',
    'Trending home tech accessory for kitchen and whole house convenience, now available via Amazon affiliate link.',
    '22% OFF',
    'https://www.amazon.com',
    'https://www.amazon.com/dp/B0GDFY12X5?ref=t_ac_view_request_product_title',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '3 hours',
    999,
    189,
    189,
    'Home'
  );
    'online',
    'active',
    'Quest Crate',
    null,
    'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=900&q=80',
    'Indie Bundle Test Event',
    'Gaming test drop for confirming category filtering and shared production rendering.',
    'LIMITED',
    'https://example.com/quest-crate/indie-rpg-bundle',
    'https://example.com/quest-crate/indie-rpg-bundle',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '32 minutes',
    timezone('utc', now()) + interval '70 minutes',
    999,
    61,
    61,
    'Gaming'
  ),
  (
    'test-online-5',
    null,
    'online',
    'active',
    'Northern Nest',
    null,
    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    'Home Essentials Test Drop',
    'Home category test deal for checking that the hosted app is reading active online deals from Supabase.',
    '30% OFF',
    'https://example.com/northern-nest/linen-event',
    'https://example.com/northern-nest/linen-event',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '14 minutes',
    timezone('utc', now()) + interval '3 hours',
    999,
    27,
    27,
    'Home'
  ),
  (
    'momcozy-kleanpal-pro',
    null,
    'online',
    'active',
    'Momcozy',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/51bYxBVtzSL._SY355_.jpg',
    'Momcozy KleanPal Pro Baby Bottle Washer',
    'All-in-One Cleaning Machine for Bottles, Pump Parts & Baby Essentials - Time-Saving & Effortless Care. Powerful cleaning with steam sterilization and comprehensive drying.',
    '33% OFF - $239.99',
    'https://amzn.to/4bNgyoT',
    'https://amzn.to/4bNgyoT',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '24 hours',
    50,
    12,
    12,
    'Home'
  ),
  (
    'samsung-watch-band-ynitec',
    null,
    'online',
    'active',
    'Ynitec',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/61Z09Ia2gOL._AC_SY395_.jpg',
    'Sport Bands Compatible with Samsung Galaxy Watch 7 6 5 4 Band 40mm 44mm',
    'No Gap Soft Silicone Strap for Smart Watch S 7 6 5 4 FE, 20mm Wristbands for GalaxyWatch. Features gapless connection technology, durable stainless steel buckle, breathable and sweat-resistant material.',
    '$5.99 (30% OFF)',
    'https://amzn.to/4bOaJYr',
    'https://amzn.to/4bOaJYr',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '12 hours',
    100,
    87,
    87,
    'Tech'
  ),
  (
    'purecozy-checkered-rug',
    null,
    'online',
    'active',
    'PureCozy',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/81SEI2WN9pL._AC_SY450_.jpg',
    'Checkered Runner Rug 2x6 for Bedroom, Brown Modern Shag Rug Super Soft Long Carpet Washable Fluffy Rugs for Living Room Bedside Sofa Home Dorm Decor Aesthetic',
    'Plush Modern Rug: PureCozy fuzzy rug has a long and plush pile, creating a cozy and luxurious feel for your home. Perfect for modern home decor, it blends seamlessly into living rooms, bedrooms. Eco-friendly packaging, rug may look flat at first—just lay it flat for 48h to regain its full thickness and fluffiness.',
    '$14.39 (30% OFF)',
    'https://amzn.to/4t0cxnS',
    'https://amzn.to/4t0cxnS',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1 minute',
    timezone('utc', now()) + interval '24 hours',
    50,
    5,
    5,
    'Home'
  )
on conflict (id) do update
set
  status = excluded.status,
  business_name = excluded.business_name,
  image_url = excluded.image_url,
  title = excluded.title,
  description = excluded.description,
  offer_text = excluded.offer_text,
  website_url = excluded.website_url,
  product_url = excluded.product_url,
  has_timer = excluded.has_timer,
  created_at = excluded.created_at,
  expires_at = excluded.expires_at,
  max_claims = excluded.max_claims,
  current_claims = excluded.current_claims,
  claim_count = excluded.claim_count,
  category = excluded.category;
