insert into public.deals (
  id,
  owner_id,
  business_type,
  status,
  business_name,
  logo_url,
  image_url,
  title,
  description,
  offer_text,
  website_url,
  product_url,
  has_timer,
  distance,
  lat,
  lng,
  created_at,
  expires_at,
  max_claims,
  current_claims,
  claim_count,
  category
)
values
  (
    'test-online-1',
    null,
    'online',
    'active',
    'Amazon',
    null,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    'Wireless Earbuds Test Drop',
    'Test online deal for verifying that the hosted LiveDrop app reads Online Drops from Supabase.',
    '25% OFF',
    'https://amzn.to/4rJ4KtO',
    'https://amzn.to/4rJ4KtO',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '10 minutes',
    timezone('utc', now()) + interval '2 hours',
    999,
    84,
    84,
    'Tech'
  ),
  (
    'test-online-2',
    null,
    'online',
    'active',
    'Pixel Forge',
    null,
    'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
    'Mechanical Keyboard Weekend Drop',
    'A seeded test deal to confirm shared database-backed Online Drops are rendering in production.',
    '40% OFF',
    'https://example.com/pixel-forge/keyboards',
    'https://example.com/pixel-forge/keyboards',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '18 minutes',
    timezone('utc', now()) + interval '95 minutes',
    999,
    126,
    126,
    'Tech'
  ),
  (
    'test-online-3',
    null,
    'online',
    'active',
    'Cloud Kicks',
    null,
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    'Sneaker Flash Sale Test',
    'Shared test card for validating Fashion online deals from the Supabase deals table.',
    'DEAL',
    'https://example.com/cloud-kicks/weekend-drop',
    'https://example.com/cloud-kicks/weekend-drop',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '150 minutes',
    999,
    42,
    42,
    'Fashion'
  ),
  (
    'test-online-4',
    null,
    'online',
    'active',
    'Quest Crate',
    null,
    'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=900&q=80',
    'Indie Bundle Test Event',
    'Gaming test drop for confirming category filtering and shared production rendering.',
    'LIMITED',
    'https://example.com/quest-crate/indie-rpg-bundle',
    'https://example.com/quest-crate/indie-rpg-bundle',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '32 minutes',
    timezone('utc', now()) + interval '70 minutes',
    999,
    61,
    61,
    'Gaming'
  ),
  (
    'test-online-5',
    null,
    'online',
    'active',
    'Northern Nest',
    null,
    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    'Home Essentials Test Drop',
    'Home category test deal for checking that the hosted app is reading active online deals from Supabase.',
    '30% OFF',
    'https://example.com/northern-nest/linen-event',
    'https://example.com/northern-nest/linen-event',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '14 minutes',
    timezone('utc', now()) + interval '3 hours',
    999,
    27,
    27,
    'Home'
  ),
  (
    'momcozy-kleanpal-pro',
    null,
    'online',
    'active',
    'Momcozy',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/51bYxBVtzSL._SY355_.jpg',
    'Momcozy KleanPal Pro Baby Bottle Washer',
    'All-in-One Cleaning Machine for Bottles, Pump Parts & Baby Essentials - Time-Saving & Effortless Care. Powerful cleaning with steam sterilization and comprehensive drying.',
    '33% OFF - $239.99',
    'https://amzn.to/4bNgyoT',
    'https://amzn.to/4bNgyoT',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '5 minutes',
    timezone('utc', now()) + interval '24 hours',
    50,
    12,
    12,
    'Home'
  ),
  (
    'samsung-watch-band-ynitec',
    null,
    'online',
    'active',
    'Ynitec',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/61Z09Ia2gOL._AC_SY395_.jpg',
    'Sport Bands Compatible with Samsung Galaxy Watch 7 6 5 4 Band 40mm 44mm',
    'No Gap Soft Silicone Strap for Smart Watch S 7 6 5 4 FE, 20mm Wristbands for GalaxyWatch. Features gapless connection technology, durable stainless steel buckle, breathable and sweat-resistant material.',
    '$5.99 (30% OFF)',
    'https://amzn.to/4bOaJYr',
    'https://amzn.to/4bOaJYr',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '2 minutes',
    timezone('utc', now()) + interval '12 hours',
    100,
    87,
    87,
    'Tech'
  ),
  (
    'purecozy-checkered-rug',
    null,
    'online',
    'active',
    'PureCozy',
    'https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif',
    'https://m.media-amazon.com/images/I/81SEI2WN9pL._AC_SY450_.jpg',
    'Checkered Runner Rug 2x6 for Bedroom, Brown Modern Shag Rug Super Soft Long Carpet Washable Fluffy Rugs for Living Room Bedside Sofa Home Dorm Decor Aesthetic',
    'Plush Modern Rug: PureCozy fuzzy rug has a long and plush pile, creating a cozy and luxurious feel for your home. Perfect for modern home decor, it blends seamlessly into living rooms, bedrooms. Eco-friendly packaging, rug may look flat at first—just lay it flat for 48h to regain its full thickness and fluffiness.',
    '$14.39 (30% OFF)',
    'https://amzn.to/4t0cxnS',
    'https://amzn.to/4t0cxnS',
    true,
    'Online',
    0,
    0,
    timezone('utc', now()) - interval '1 minute',
    timezone('utc', now()) + interval '24 hours',
    50,
    5,
    5,
    'Home'
  )
on conflict (id) do update
set
  status = excluded.status,
  business_name = excluded.business_name,
  image_url = excluded.image_url,
  title = excluded.title,
  description = excluded.description,
  offer_text = excluded.offer_text,
  website_url = excluded.website_url,
  product_url = excluded.product_url,
  has_timer = excluded.has_timer,
  created_at = excluded.created_at,
  expires_at = excluded.expires_at,
  max_claims = excluded.max_claims,
  current_claims = excluded.current_claims,
  claim_count = excluded.claim_count,
  category = excluded.category;
