import { Deal, UserLocation } from '../types';

/**
 * Generates a set of realistic demo deals around a center location.
 */
export function generateSeededDeals(center: UserLocation): Deal[] {
  const deals: Deal[] = [
    {
      id: 'seed-1',
      businessType: 'local',
      businessName: 'The Local Grind',
      title: 'Flash Coffee Special',
      description: 'Our barista just made too many lattes! Grab any large latte for just $2. First come, first served.',
      offerText: '$2 LARGE LATTES',
      distance: '0.4 miles',
      ...getOffsetLocation(center, 0.4),
      createdAt: Date.now(),
      expiresAt: Date.now() + 20 * 60 * 1000,
      maxClaims: 15,
      currentClaims: 4,
      claimCount: 4,
      category: 'Coffee'
    },
    {
      id: 'seed-2',
      businessType: 'local',
      businessName: 'Burger Bliss',
      title: 'Lunch Rush Bonus',
      description: 'Free side of truffle fries with any signature burger purchase. Mention LiveDrop at the counter.',
      offerText: 'FREE TRUFFLE FRIES',
      distance: '1.2 miles',
      ...getOffsetLocation(center, 1.2),
      createdAt: Date.now(),
      expiresAt: Date.now() + 35 * 60 * 1000,
      maxClaims: 20,
      currentClaims: 18, // Almost sold out
      claimCount: 18,
      category: 'Fast Food'
    },
    {
      id: 'seed-3',
      businessType: 'local',
      businessName: 'Zen Yoga Studio',
      title: 'Last Minute Mat Space',
      description: 'We have 3 spots left in our 12:30 PM Vinyasa Flow. Claim this drop for a $10 drop-in rate!',
      offerText: '$10 YOGA CLASS',
      distance: '2.8 miles',
      ...getOffsetLocation(center, 2.8),
      createdAt: Date.now(),
      expiresAt: Date.now() + 45 * 60 * 1000,
      maxClaims: 3,
      currentClaims: 0,
      claimCount: 0,
      category: 'Fitness'
    },
    {
      id: 'seed-4',
      businessType: 'local',
      businessName: 'Taco Fiesta',
      title: 'Taco Tuesday Early Bird',
      description: 'Get a platter of 4 street tacos and a soda for $8. Valid for the next hour only.',
      offerText: '$8 TACO PLATTER',
      distance: '4.5 miles',
      ...getOffsetLocation(center, 4.5),
      createdAt: Date.now(),
      expiresAt: Date.now() + 60 * 60 * 1000,
      maxClaims: 30,
      currentClaims: 12,
      claimCount: 12,
      category: 'Fast Food'
    },
    {
      id: 'seed-5',
      businessType: 'local',
      businessName: 'Clean & Gleam',
      title: 'Express Wash Discount',
      description: 'Drive through now and get our Premium Shine wash for the price of a Basic wash.',
      offerText: 'FREE WASH UPGRADE',
      distance: '7.0 miles',
      ...getOffsetLocation(center, 7.0),
      createdAt: Date.now(),
      expiresAt: Date.now() + 90 * 60 * 1000,
      maxClaims: 10,
      currentClaims: 10, // SOLD OUT
      claimCount: 10,
      category: 'Home'
    },
    {
      id: 'seed-6',
      businessType: 'local',
      businessName: 'The Book Nook',
      title: 'Mystery Book Drop',
      description: 'We just put out a box of "Blind Date with a Book". Claim this to get one for free with any purchase!',
      offerText: 'FREE MYSTERY BOOK',
      distance: '12.0 miles',
      ...getOffsetLocation(center, 12.0),
      createdAt: Date.now(),
      expiresAt: Date.now() + 120 * 60 * 1000,
      maxClaims: 12,
      currentClaims: 5,
      claimCount: 5,
      category: 'Home'
    },
    {
      id: 'seed-7',
      businessType: 'local',
      businessName: 'Smoothie Station',
      title: 'Post-Workout Refresher',
      description: 'All protein smoothies are 30% off for the next 40 minutes. Refuel your body!',
      offerText: '30% OFF SMOOTHIES',
      distance: '0.8 miles',
      ...getOffsetLocation(center, 0.8),
      createdAt: Date.now(),
      expiresAt: Date.now() + 40 * 60 * 1000,
      maxClaims: 25,
      currentClaims: 2,
      claimCount: 2,
      category: 'Fitness'
    },
    {
      id: 'seed-8',
      businessType: 'local',
      businessName: 'Pet Palace',
      title: 'Treat Jar Refill',
      description: 'Bring your furry friend in and get a free bag of organic treats with any grooming service.',
      offerText: 'FREE DOG TREATS',
      distance: '3.5 miles',
      ...getOffsetLocation(center, 3.5),
      createdAt: Date.now(),
      expiresAt: Date.now() + 180 * 60 * 1000,
      maxClaims: 15,
      currentClaims: 15, // SOLD OUT
      claimCount: 15,
      category: 'Pet'
    }
  ];

  return deals;
}

export function generateSeededOnlineDeals(): Deal[] {
  const now = Date.now();

  return [
    {
      id: 'online-seed-0',
      businessType: 'online',
      businessName: 'Amazon Fire TV',
      title: 'Amazon Fire TV Stick 4K Plus (Newest Model) with AI-Powered Fire TV Search and Wi-Fi 6',
      description: 'Streaming stick deal with 4K support, AI-powered Fire TV search, and faster Wi-Fi 6 playback.',
      offerText: '$49.99 -> $29.99',
      originalPrice: 49.99,
      discountPercent: 40,
      affiliateUrl: 'https://www.amazon.com/dp/B0F7Z4QZTT',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0F7Z4QZTT',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 1 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 126,
      claimCount: 126,
      category: 'Tech',
    },
    {
      id: 'online-seed-google-pixel',
      businessType: 'online',
      businessName: 'Google',
      title: 'Google Pixel 8 - Unlocked Android Smartphone',
      description: 'Google Pixel 8 with 128GB, 24-Hour Battery, and Google Assistant. Fast-charging, unlocked, and ready for any carrier.',
      offerText: 'Amazon Deal',
      originalPrice: 699.00,
      currentPrice: 549.00,
      discountPercent: 21,
      affiliateUrl: 'https://amzn.to/4lUylPN',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/Google-Pixel-Smartphone-Assistant-Fast-Charging/dp/B0FFTRK635',
      imageUrl: 'https://m.media-amazon.com/images/I/71Q+JQkNQbL._AC_SL1500_.jpg',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 5 * 60 * 1000,
      expiresAt: now + 120 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 0,
      claimCount: 0,
      category: 'Tech',
    },
    {
      id: 'online-seed-0b',
      businessType: 'online',
      businessName: 'D-Link',
      title: 'D-Link Pro Series Compact Full HD Pan & Tilt Wi-Fi Camera',
      description: 'Compact indoor security camera with pan-and-tilt coverage, Full HD video, and smart home monitoring.',
      offerText: '$79.99 -> $29.99',
      originalPrice: 79.99,
      discountPercent: 63,
      affiliateUrl: 'https://www.amazon.com/dp/B00PS13QSO',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B00PS13QSO',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 90 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 92,
      claimCount: 92,
      category: 'Home',
    },
    {
      id: 'online-seed-1',
      businessType: 'online',
      businessName: 'Orgain',
      title: 'Orgain Organic Wonder Gut Fiber Supplement Powder, Strawberry Lemonade',
      description: 'Digestive fiber powder deal with a steep markdown and frequent coupon-style stacking on Amazon.',
      offerText: '$29.99 -> $9.73',
      originalPrice: 29.99,
      discountPercent: 68,
      affiliateUrl: 'https://www.amazon.com/dp/B0CXV56J4G',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0CXV56J4G',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 2 * 60 * 1000,
      expiresAt: now + 150 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 51,
      claimCount: 51,
      category: 'Home',
    },
    {
      id: 'online-seed-2',
      businessType: 'online',
      businessName: 'KK Lights',
      title: 'Cordless Table Lamp Rechargeable Gold, 2-Pack 5000mAh Battery Lamps',
      description: 'Rechargeable cordless lamp set with a gold finish and promo-style pricing for bedside or patio setups.',
      offerText: 'PROMO PRICE ~ $14.99',
      affiliateUrl: 'https://www.amazon.com/dp/B0DJYFJGQW',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0DJYFJGQW',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 6 * 60 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 38,
      claimCount: 38,
      category: 'Home',
    },
    {
      id: 'online-seed-home-1',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'GRLEAF 70" Sofa Table with Built-in Power Strip (2 AC Outlets & 2 USB Ports) - Rustic Brown',
      description: 'Long narrow sofa table with built-in outlets and USB ports, made for behind-the-couch setups and compact home-office spaces.',
      offerText: 'HOME DROP',
      imageUrl: 'https://m.media-amazon.com/images/I/71LbDwKqAvL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/GRLEAF-Narrow-Console-Built-Outlets/dp/B0DQXZ4J2Y',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/GRLEAF-Narrow-Console-Built-Outlets/dp/B0DQXZ4J2Y',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 2 * 60 * 1000,
      expiresAt: now + 110 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 54,
      claimCount: 54,
      category: 'Home',
    },
    {
      id: 'online-seed-home-2',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'JESONVID Solid Wood Console Table with 2 Drawers - Blue',
      description: 'Solid wood console table with dual drawers and layered storage shelving for entryway, living room, or office use.',
      offerText: 'LIMITED HOME DEAL',
      imageUrl: 'https://m.media-amazon.com/images/I/71xgtQ+NvNL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/Console-Drawers-Multilayer-Entryway-Office-Blue/dp/B0BDFLV9SZ',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/Console-Drawers-Multilayer-Entryway-Office-Blue/dp/B0BDFLV9SZ',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 3 * 60 * 1000,
      expiresAt: now + 125 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 41,
      claimCount: 41,
      category: 'Home',
    },
    {
      id: 'online-seed-home-3',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Modern Upholstered Accent Chair',
      description: 'Modern fabric armchair with solid wood legs and a compact accent-chair silhouette for bedroom, balcony, or living room corners.',
      offerText: 'FEATURED HOME FIND',
      imageUrl: 'https://m.media-amazon.com/images/I/61I4-1dK6EL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/NABEIM-Upholstered-Armchair-Practical-Fashionable/dp/B09C1BWF1D',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/NABEIM-Upholstered-Armchair-Practical-Fashionable/dp/B09C1BWF1D',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 4 * 60 * 1000,
      expiresAt: now + 140 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 36,
      claimCount: 36,
      category: 'Home',
    },
    {
      id: 'online-seed-home-4',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'DORTALA Nightstand Wooden 2-Tier Couch Sofa Side Table with Drawer',
      description: 'Compact gray side table with drawer and lower shelf storage, built for bedside or living-room corners.',
      offerText: 'FLASH HOME SALE',
      imageUrl: 'https://m.media-amazon.com/images/I/51WEji-E7PL._AC_SL1200_.jpg',
      affiliateUrl: 'https://www.amazon.com/DORTALA-Nightstand-Storage-Mufti-Functional-Furniture/dp/B08L9C6332',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/DORTALA-Nightstand-Storage-Mufti-Functional-Furniture/dp/B08L9C6332',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 5 * 60 * 1000,
      expiresAt: now + 100 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 29,
      claimCount: 29,
      category: 'Home',
    },
    {
      id: 'online-seed-home-5',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Alaterre Furniture Fluted Solid Wood Console Table - Light Oak',
      description: 'Modern fluted entryway console table with a lower shelf and a clean light-oak finish for hallway or couch-behind styling.',
      offerText: 'JUST DROPPED',
      imageUrl: 'https://m.media-amazon.com/images/I/91PnpJzpFvL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/Alaterre-Furniture-Fluted-Solid-Console/dp/B0GGTP979F',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/Alaterre-Furniture-Fluted-Solid-Console/dp/B0GGTP979F',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 6 * 60 * 1000,
      expiresAt: now + 135 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 48,
      claimCount: 48,
      category: 'Home',
    },
    {
      id: 'online-seed-4b',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Amazon Essentials Men\'s Tee Deal Drop',
      description: 'A fresh Amazon Essentials men\'s t-shirt search drop with affordable basics, multipacks, and everyday wardrobe picks ready to browse now.',
      offerText: 'FASHION DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=amazon+essentials+mens+t+shirt',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=amazon+essentials+mens+t+shirt',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 45 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 68,
      claimCount: 68,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4c',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Cheap Hoodies for Men Flash Sale',
      description: 'Browse budget-friendly men\'s hoodies, fleece layers, and everyday cold-weather essentials in this Amazon fashion search deal.',
      offerText: 'FLASH SALE',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=cheap+hoodies+men',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=cheap+hoodies+men',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 60 * 1000,
      expiresAt: now + 110 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 91,
      claimCount: 91,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4d',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Gildan Hoodie Everyday Deal',
      description: 'A Gildan hoodie search page packed with casual fleece options, everyday layers, and easy-price wardrobe staples.',
      offerText: 'DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=gildan+hoodie',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=gildan+hoodie',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 75 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 57,
      claimCount: 57,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4e',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Amazon Essentials Tank Top Multi-Pack Save',
      description: 'A warm-weather basics search featuring Amazon Essentials tank tops, loungewear staples, and simple everyday layering pieces.',
      offerText: 'LIMITED DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=amazon+essentials+tank+top',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=amazon+essentials+tank+top',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 90 * 1000,
      expiresAt: now + 140 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 42,
      claimCount: 42,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4f',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Men\'s Fashion Deals Roundup',
      description: 'An Amazon men\'s fashion search page with mixed apparel deals, wardrobe basics, and current markdowns gathered into one browsing destination.',
      offerText: 'TRENDING DEALS',
      imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=mens+fashion+deals',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=mens+fashion+deals',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 105 * 1000,
      expiresAt: now + 125 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 133,
      claimCount: 133,
      category: 'Fashion',
    },
    {
      id: 'online-seed-31',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Beats Studio Pro Noise-Canceling Headphones',
      description: 'Premium over-ear wireless headphones with personalized spatial audio and all-day battery are on a limited Amazon drop right now.',
      offerText: '18% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
      productUrl: 'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 12 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000 + 15 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 167,
      claimCount: 167,
      category: 'Tech',
    },
    {
      id: 'online-seed-32',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Smart Desk Lamp Deal Drop',
      description: 'A compact LED desk lamp with adjustable brightness and a clean home-office look is moving fast in today’s Amazon event.',
      offerText: 'DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 22 * 60 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 121,
      claimCount: 121,
      category: 'Home',
    },
    {
      id: 'online-seed-33',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Everyday Sneaker Flash Markdown',
      description: 'Lightweight casual sneakers are part of a quick online apparel markdown with fresh sizes still in stock.',
      offerText: '20% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 8 * 60 * 1000,
      expiresAt: now + 150 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 44,
      claimCount: 44,
      category: 'Fashion',
    },
    {
      id: 'online-seed-35',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Portable Charger Quick Save',
      description: 'A travel-friendly battery pack with USB-C fast charging is part of a fresh mobile-tech deal drop today.',
      offerText: '25% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 18 * 60 * 1000,
      expiresAt: now + 70 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 152,
      claimCount: 152,
      category: 'Tech',
    },
    {
      id: 'momcozy-kleanpal-pro',
      businessType: 'online',
      businessName: 'Momcozy',
      title: 'Momcozy KleanPal Pro Baby Bottle Washer',
      description: 'All-in-One Cleaning Machine for Bottles, Pump Parts & Baby Essentials - Time-Saving & Effortless Care. Powerful cleaning with steam sterilization and comprehensive drying.',
      offerText: '33% OFF - $239.99',
      imageUrl: 'https://m.media-amazon.com/images/I/51bYxBVtzSL._SY355_.jpg',
      affiliateUrl: 'https://amzn.to/4bNgyoT',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4bNgyoT',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 5 * 60 * 1000,
      expiresAt: now + 24 * 60 * 60 * 1000,
      maxClaims: 50,
      currentClaims: 12,
      claimCount: 12,
      category: 'Home',
    },
    {
      id: 'samsung-watch-band-ynitec',
      businessType: 'online',
      businessName: 'Ynitec',
      title: 'Sport Bands Compatible with Samsung Galaxy Watch 7 6 5 4 Band 40mm 44mm',
      description: 'No Gap Soft Silicone Strap for Smart Watch S 7 6 5 4 FE, 20mm Wristbands for GalaxyWatch. Features gapless connection technology, durable stainless steel buckle, breathable and sweat-resistant material.',
      offerText: '$5.99 (30% OFF)',
      imageUrl: 'https://m.media-amazon.com/images/I/61Z09Ia2gOL._AC_SY395_.jpg',
      affiliateUrl: 'https://amzn.to/4bOaJYr',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4bOaJYr',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 2 * 60 * 1000,
      expiresAt: now + 12 * 60 * 60 * 1000,
      maxClaims: 100,
      currentClaims: 87,
      claimCount: 87,
      category: 'Tech',
    },
    {
      id: 'purecozy-checkered-rug',
      businessType: 'online',
      businessName: 'PureCozy',
      title: 'Checkered Runner Rug 2x6 for Bedroom, Brown Modern Shag Rug Super Soft Long Carpet Washable Fluffy Rugs for Living Room Bedside Sofa Home Dorm Decor Aesthetic',
      description: 'Plush Modern Rug: PureCozy fuzzy rug has a long and plush pile, creating a cozy and luxurious feel for your home. Perfect for modern home decor, it blends seamlessly into living rooms, bedrooms. Eco-friendly packaging, rug may look flat at first—just lay it flat for 48h to regain its full thickness and fluffiness.',
      offerText: '$14.39 (30% OFF)',
      imageUrl: 'https://m.media-amazon.com/images/I/81SEI2WN9pL._AC_SY450_.jpg',
      affiliateUrl: 'https://amzn.to/4t0cxnS',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4t0cxnS',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 1 * 60 * 1000,
      expiresAt: now + 24 * 60 * 60 * 1000,
      maxClaims: 50,
      currentClaims: 5,
      claimCount: 5,
      category: 'Home',
    },
    {
      id: 'online-seed-36',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Smart Home Essential: Award-Winning Kitchen & Home Hub (B0GHRPJ8SY)',
      description: 'Amazon-listed smart home device optimized for modern kitchen and home use, now on a trending discount via affiliate deal.',
      offerText: '19% OFF',
      originalPrice: 249.99,
      discountPercent: 19,
      imageUrl: 'https://m.media-amazon.com/images/I/61A5VWc9rBL._AC_SL1200_.jpg',
      affiliateUrl: 'https://amzn.to/4lTHRlZ',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0GHRPJ8SY?ref=t_ac_view_request_product_title&th=1',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 2 * 60 * 1000,
      expiresAt: now + 4 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 174,
      claimCount: 174,
      category: 'Home',
    },
    {
      id: 'online-seed-37',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Trending Home Pick: Smart Kitchen Essential (B0GDFY12X5)',
      description: 'Trending home tech accessory for kitchen and whole house convenience, now available via Amazon affiliate link.',
      offerText: '22% OFF',
      originalPrice: 199.99,
      discountPercent: 22,
      imageUrl: 'https://m.media-amazon.com/images/I/61VjXKxzD7L._AC_SL1200_.jpg',
      affiliateUrl: 'https://amzn.to/4bwgTgS',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0GDFY12X5?ref=t_ac_view_request_product_title',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 2 * 60 * 1000,
      expiresAt: now + 3 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 189,
      claimCount: 189,
      category: 'Home',
    },
  ];
}

/**
 * Helper to calculate a lat/lng offset based on miles.
 * This is a rough approximation for demo purposes.
 * 1 degree lat is ~69 miles.
 * 1 degree lng is ~69 * cos(lat) miles.
 */
function getOffsetLocation(center: UserLocation, miles: number): { lat: number; lng: number } {
  const latOffset = (miles / 69) * (Math.random() > 0.5 ? 1 : -1) * (0.7 + Math.random() * 0.3);
  const lngOffset = (miles / (69 * Math.cos(center.lat * Math.PI / 180))) * (Math.random() > 0.5 ? 1 : -1) * (0.7 + Math.random() * 0.3);
  
  return {
    lat: center.lat + latOffset,
    lng: center.lng + lngOffset
  };
}
