import { Deal, UserLocation } from '../types';

/**
 * Generates a set of realistic demo deals around a center location.
 */
export function generateSeededDeals(center: UserLocation): Deal[] {
  const deals: Deal[] = [
    {
      id: 'seed-1',
      businessType: 'local',
      businessName: 'The Local Grind',
      title: 'Flash Coffee Special',
      description: 'Our barista just made too many lattes! Grab any large latte for just $2. First come, first served.',
      offerText: '$2 LARGE LATTES',
      distance: '0.4 miles',
      ...getOffsetLocation(center, 0.4),
      createdAt: Date.now(),
      expiresAt: Date.now() + 20 * 60 * 1000,
      maxClaims: 15,
      currentClaims: 4,
      claimCount: 4,
      category: 'Coffee'
    },
    {
      id: 'seed-2',
      businessType: 'local',
      businessName: 'Burger Bliss',
      title: 'Lunch Rush Bonus',
      description: 'Free side of truffle fries with any signature burger purchase. Mention LiveDrop at the counter.',
      offerText: 'FREE TRUFFLE FRIES',
      distance: '1.2 miles',
      ...getOffsetLocation(center, 1.2),
      createdAt: Date.now(),
      expiresAt: Date.now() + 35 * 60 * 1000,
      maxClaims: 20,
      currentClaims: 18, // Almost sold out
      claimCount: 18,
      category: 'Fast Food'
    },
    {
      id: 'seed-3',
      businessType: 'local',
      businessName: 'Zen Yoga Studio',
      title: 'Last Minute Mat Space',
      description: 'We have 3 spots left in our 12:30 PM Vinyasa Flow. Claim this drop for a $10 drop-in rate!',
      offerText: '$10 YOGA CLASS',
      distance: '2.8 miles',
      ...getOffsetLocation(center, 2.8),
      createdAt: Date.now(),
      expiresAt: Date.now() + 45 * 60 * 1000,
      maxClaims: 3,
      currentClaims: 0,
      claimCount: 0,
      category: 'Fitness'
    },
    {
      id: 'seed-4',
      businessType: 'local',
      businessName: 'Taco Fiesta',
      title: 'Taco Tuesday Early Bird',
      description: 'Get a platter of 4 street tacos and a soda for $8. Valid for the next hour only.',
      offerText: '$8 TACO PLATTER',
      distance: '4.5 miles',
      ...getOffsetLocation(center, 4.5),
      createdAt: Date.now(),
      expiresAt: Date.now() + 60 * 60 * 1000,
      maxClaims: 30,
      currentClaims: 12,
      claimCount: 12,
      category: 'Fast Food'
    },
    {
      id: 'seed-5',
      businessType: 'local',
      businessName: 'Clean & Gleam',
      title: 'Express Wash Discount',
      description: 'Drive through now and get our Premium Shine wash for the price of a Basic wash.',
      offerText: 'FREE WASH UPGRADE',
      distance: '7.0 miles',
      ...getOffsetLocation(center, 7.0),
      createdAt: Date.now(),
      expiresAt: Date.now() + 90 * 60 * 1000,
      maxClaims: 10,
      currentClaims: 10, // SOLD OUT
      claimCount: 10,
      category: 'Home'
    },
    {
      id: 'seed-6',
      businessType: 'local',
      businessName: 'The Book Nook',
      title: 'Mystery Book Drop',
      description: 'We just put out a box of "Blind Date with a Book". Claim this to get one for free with any purchase!',
      offerText: 'FREE MYSTERY BOOK',
      distance: '12.0 miles',
      ...getOffsetLocation(center, 12.0),
      createdAt: Date.now(),
      expiresAt: Date.now() + 120 * 60 * 1000,
      maxClaims: 12,
      currentClaims: 5,
      claimCount: 5,
      category: 'Home'
    },
    {
      id: 'seed-7',
      businessType: 'local',
      businessName: 'Smoothie Station',
      title: 'Post-Workout Refresher',
      description: 'All protein smoothies are 30% off for the next 40 minutes. Refuel your body!',
      offerText: '30% OFF SMOOTHIES',
      distance: '0.8 miles',
      ...getOffsetLocation(center, 0.8),
      createdAt: Date.now(),
      expiresAt: Date.now() + 40 * 60 * 1000,
      maxClaims: 25,
      currentClaims: 2,
      claimCount: 2,
      category: 'Fitness'
    },
    {
      id: 'seed-8',
      businessType: 'local',
      businessName: 'Pet Palace',
      title: 'Treat Jar Refill',
      description: 'Bring your furry friend in and get a free bag of organic treats with any grooming service.',
      offerText: 'FREE DOG TREATS',
      distance: '3.5 miles',
      ...getOffsetLocation(center, 3.5),
      createdAt: Date.now(),
      expiresAt: Date.now() + 180 * 60 * 1000,
      maxClaims: 15,
      currentClaims: 15, // SOLD OUT
      claimCount: 15,
      category: 'Pet'
    }
  ];

  return deals;
}

export function generateSeededOnlineDeals(): Deal[] {
  const now = Date.now();

  return [
    {
      id: 'online-seed-0',
      businessType: 'online',
      businessName: 'Amazon Fire TV',
      title: 'Amazon Fire TV Stick 4K Plus (Newest Model) with AI-Powered Fire TV Search and Wi-Fi 6',
      description: 'Streaming stick deal with 4K support, AI-powered Fire TV search, and faster Wi-Fi 6 playback.',
      offerText: '$49.99 -> $29.99',
      originalPrice: 49.99,
      discountPercent: 40,
      affiliateUrl: 'https://www.amazon.com/dp/B0F7Z4QZTT',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0F7Z4QZTT',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 1 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 126,
      claimCount: 126,
      category: 'Tech',
    },
    {
      id: 'online-seed-0b',
      businessType: 'online',
      businessName: 'D-Link',
      title: 'D-Link Pro Series Compact Full HD Pan & Tilt Wi-Fi Camera',
      description: 'Compact indoor security camera with pan-and-tilt coverage, Full HD video, and smart home monitoring.',
      offerText: '$79.99 -> $29.99',
      originalPrice: 79.99,
      discountPercent: 63,
      affiliateUrl: 'https://www.amazon.com/dp/B00PS13QSO',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B00PS13QSO',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 90 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 92,
      claimCount: 92,
      category: 'Home',
    },
    {
      id: 'online-seed-1',
      businessType: 'online',
      businessName: 'Orgain',
      title: 'Orgain Organic Wonder Gut Fiber Supplement Powder, Strawberry Lemonade',
      description: 'Digestive fiber powder deal with a steep markdown and frequent coupon-style stacking on Amazon.',
      offerText: '$29.99 -> $9.73',
      originalPrice: 29.99,
      discountPercent: 68,
      affiliateUrl: 'https://www.amazon.com/dp/B0CXV56J4G',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0CXV56J4G',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 2 * 60 * 1000,
      expiresAt: now + 150 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 51,
      claimCount: 51,
      category: 'Home',
    },
    {
      id: 'online-seed-2',
      businessType: 'online',
      businessName: 'KK Lights',
      title: 'Cordless Table Lamp Rechargeable Gold, 2-Pack 5000mAh Battery Lamps',
      description: 'Rechargeable cordless lamp set with a gold finish and promo-style pricing for bedside or patio setups.',
      offerText: 'PROMO PRICE ~ $14.99',
      affiliateUrl: 'https://www.amazon.com/dp/B0DJYFJGQW',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/dp/B0DJYFJGQW',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 6 * 60 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 38,
      claimCount: 38,
      category: 'Home',
    },
    {
      id: 'online-seed-home-1',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'GRLEAF 70" Sofa Table with Built-in Power Strip (2 AC Outlets & 2 USB Ports) - Rustic Brown',
      description: 'Long narrow sofa table with built-in outlets and USB ports, made for behind-the-couch setups and compact home-office spaces.',
      offerText: 'HOME DROP',
      imageUrl: 'https://m.media-amazon.com/images/I/71LbDwKqAvL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/GRLEAF-Narrow-Console-Built-Outlets/dp/B0DQXZ4J2Y',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/GRLEAF-Narrow-Console-Built-Outlets/dp/B0DQXZ4J2Y',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 2 * 60 * 1000,
      expiresAt: now + 110 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 54,
      claimCount: 54,
      category: 'Home',
    },
    {
      id: 'online-seed-home-2',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'JESONVID Solid Wood Console Table with 2 Drawers - Blue',
      description: 'Solid wood console table with dual drawers and layered storage shelving for entryway, living room, or office use.',
      offerText: 'LIMITED HOME DEAL',
      imageUrl: 'https://m.media-amazon.com/images/I/71xgtQ+NvNL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/Console-Drawers-Multilayer-Entryway-Office-Blue/dp/B0BDFLV9SZ',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/Console-Drawers-Multilayer-Entryway-Office-Blue/dp/B0BDFLV9SZ',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 3 * 60 * 1000,
      expiresAt: now + 125 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 41,
      claimCount: 41,
      category: 'Home',
    },
    {
      id: 'online-seed-home-3',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Modern Upholstered Accent Chair',
      description: 'Modern fabric armchair with solid wood legs and a compact accent-chair silhouette for bedroom, balcony, or living room corners.',
      offerText: 'FEATURED HOME FIND',
      imageUrl: 'https://m.media-amazon.com/images/I/61I4-1dK6EL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/NABEIM-Upholstered-Armchair-Practical-Fashionable/dp/B09C1BWF1D',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/NABEIM-Upholstered-Armchair-Practical-Fashionable/dp/B09C1BWF1D',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 4 * 60 * 1000,
      expiresAt: now + 140 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 36,
      claimCount: 36,
      category: 'Home',
    },
    {
      id: 'online-seed-home-4',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'DORTALA Nightstand Wooden 2-Tier Couch Sofa Side Table with Drawer',
      description: 'Compact gray side table with drawer and lower shelf storage, built for bedside or living-room corners.',
      offerText: 'FLASH HOME SALE',
      imageUrl: 'https://m.media-amazon.com/images/I/51WEji-E7PL._AC_SL1200_.jpg',
      affiliateUrl: 'https://www.amazon.com/DORTALA-Nightstand-Storage-Mufti-Functional-Furniture/dp/B08L9C6332',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/DORTALA-Nightstand-Storage-Mufti-Functional-Furniture/dp/B08L9C6332',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 5 * 60 * 1000,
      expiresAt: now + 100 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 29,
      claimCount: 29,
      category: 'Home',
    },
    {
      id: 'online-seed-home-5',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Alaterre Furniture Fluted Solid Wood Console Table - Light Oak',
      description: 'Modern fluted entryway console table with a lower shelf and a clean light-oak finish for hallway or couch-behind styling.',
      offerText: 'JUST DROPPED',
      imageUrl: 'https://m.media-amazon.com/images/I/91PnpJzpFvL._AC_SL1500_.jpg',
      affiliateUrl: 'https://www.amazon.com/Alaterre-Furniture-Fluted-Solid-Console/dp/B0GGTP979F',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/Alaterre-Furniture-Fluted-Solid-Console/dp/B0GGTP979F',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 6 * 60 * 1000,
      expiresAt: now + 135 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 48,
      claimCount: 48,
      category: 'Home',
    },
    {
      id: 'online-seed-3',
      businessType: 'online',
      businessName: 'Glow Haus',
      title: 'Hydration Serum Flash Sale',
      description: 'A skin-barrier favorite with a limited-time online drop for today only.',
      offerText: '25% OFF SERUM',
      imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/glow-haus',
      productUrl: 'https://example.com/glow-haus/hydration-serum',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 10 * 60 * 1000,
      expiresAt: now + 55 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 38,
      claimCount: 38,
      category: 'Digital',
    },
    {
      id: 'online-seed-4',
      businessType: 'online',
      businessName: 'Cloud Kicks',
      title: 'Weekend Sneaker Drop',
      description: 'Members get first access to our lightweight runners with a same-day online discount.',
      offerText: '$30 OFF TODAY',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/cloud-kicks',
      productUrl: 'https://example.com/cloud-kicks/weekend-drop',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 30 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 24,
      claimCount: 24,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4b',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Amazon Essentials Men\'s Tee Deal Drop',
      description: 'A fresh Amazon Essentials men\'s t-shirt search drop with affordable basics, multipacks, and everyday wardrobe picks ready to browse now.',
      offerText: 'FASHION DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=amazon+essentials+mens+t+shirt',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=amazon+essentials+mens+t+shirt',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 45 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 68,
      claimCount: 68,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4c',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Cheap Hoodies for Men Flash Sale',
      description: 'Browse budget-friendly men\'s hoodies, fleece layers, and everyday cold-weather essentials in this Amazon fashion search deal.',
      offerText: 'FLASH SALE',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=cheap+hoodies+men',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=cheap+hoodies+men',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 60 * 1000,
      expiresAt: now + 110 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 91,
      claimCount: 91,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4d',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Gildan Hoodie Everyday Deal',
      description: 'A Gildan hoodie search page packed with casual fleece options, everyday layers, and easy-price wardrobe staples.',
      offerText: 'DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=gildan+hoodie',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=gildan+hoodie',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 75 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 57,
      claimCount: 57,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4e',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Amazon Essentials Tank Top Multi-Pack Save',
      description: 'A warm-weather basics search featuring Amazon Essentials tank tops, loungewear staples, and simple everyday layering pieces.',
      offerText: 'LIMITED DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=amazon+essentials+tank+top',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=amazon+essentials+tank+top',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 90 * 1000,
      expiresAt: now + 140 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 42,
      claimCount: 42,
      category: 'Fashion',
    },
    {
      id: 'online-seed-4f',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Men\'s Fashion Deals Roundup',
      description: 'An Amazon men\'s fashion search page with mixed apparel deals, wardrobe basics, and current markdowns gathered into one browsing destination.',
      offerText: 'TRENDING DEALS',
      imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      affiliateUrl: 'https://www.amazon.com/s?k=mens+fashion+deals',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://www.amazon.com/s?k=mens+fashion+deals',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 105 * 1000,
      expiresAt: now + 125 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 133,
      claimCount: 133,
      category: 'Fashion',
    },
    {
      id: 'online-seed-5',
      businessType: 'online',
      businessName: 'Brew Supply Co.',
      title: 'Cold Brew Starter Bundle',
      description: 'Starter kit bundle drop with filters, beans, and a brewer for new subscribers.',
      offerText: 'FREE SHIPPING + 15% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/brew-supply',
      productUrl: 'https://example.com/brew-supply/cold-brew-bundle',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 90 * 60 * 1000,
      expiresAt: now + 7 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 11,
      claimCount: 11,
      category: 'Home',
    },
    {
      id: 'online-seed-6',
      businessType: 'online',
      businessName: 'Pixel Forge',
      title: '50% OFF Mechanical Keyboards',
      description: 'Hot-swappable RGB boards and compact layouts are moving fast in today’s flash drop.',
      offerText: 'FROM $129 → $64',
      imageUrl: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/pixel-forge',
      productUrl: 'https://example.com/pixel-forge/keyboards',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 12 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000 + 15 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 112,
      claimCount: 112,
      category: 'Tech',
    },
    {
      id: 'online-seed-7',
      businessType: 'online',
      businessName: 'Signal Mobile',
      title: 'Wireless Earbuds Weekend Price Cut',
      description: 'Noise-canceling earbuds with all-day battery are part of a limited online markdown.',
      offerText: '$89 → $59',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/signal-mobile',
      productUrl: 'https://example.com/signal-mobile/earbuds',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 28 * 60 * 1000,
      expiresAt: now + 3 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 78,
      claimCount: 78,
      category: 'Tech',
    },
    {
      id: 'online-seed-8',
      businessType: 'online',
      businessName: 'Orbit Setup',
      title: 'Laptop Stand Bundle Deal',
      description: 'Get a metal stand, cable organizer, and mouse pad in one neat work-from-home pack.',
      offerText: 'BUNDLE 35% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/orbit-setup',
      productUrl: 'https://example.com/orbit-setup/bundle',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 5 * 60 * 60 * 1000,
      expiresAt: now + 5 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 16,
      claimCount: 16,
      category: 'Tech',
    },
    {
      id: 'online-seed-9',
      businessType: 'online',
      businessName: 'Nike',
      title: 'Nike Flash Sale – Up to 40% OFF',
      description: 'Running gear, sneakers, and training staples are discounted for a short online window.',
      offerText: 'UP TO 40% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/nike',
      productUrl: 'https://example.com/nike/flash-sale',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 8 * 60 * 1000,
      expiresAt: now + 4 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 140,
      claimCount: 140,
      category: 'Fashion',
    },
    {
      id: 'online-seed-10',
      businessType: 'online',
      businessName: 'Aster Apparel',
      title: 'Spring Layering Edit',
      description: 'Soft tees, knits, and overshirts pulled into one quick seasonal markdown.',
      offerText: 'BUY 2, GET 1 FREE',
      imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/aster-apparel',
      productUrl: 'https://example.com/aster-apparel/spring-edit',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 42 * 60 * 1000,
      expiresAt: now + 5 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 52,
      claimCount: 52,
      category: 'Fashion',
    },
    {
      id: 'online-seed-11',
      businessType: 'online',
      businessName: 'Luna Bags',
      title: 'Mini Crossbody Restock Drop',
      description: 'A fresh run of best-selling crossbodies just landed with a first-day online discount.',
      offerText: '$74 → $54',
      imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/luna-bags',
      productUrl: 'https://example.com/luna-bags/crossbody-drop',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 16 * 60 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 64,
      claimCount: 64,
      category: 'Fashion',
    },
    {
      id: 'online-seed-12',
      businessType: 'online',
      businessName: 'Thread House',
      title: 'Denim Days Online Event',
      description: 'Straight, relaxed, and wide-leg fits are all part of a one-day online denim event.',
      offerText: '2 PAIRS FOR $99',
      imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/thread-house',
      productUrl: 'https://example.com/thread-house/denim-days',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 3 * 60 * 60 * 1000,
      expiresAt: now + 3 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 19,
      claimCount: 19,
      category: 'Fashion',
    },
    {
      id: 'online-seed-16',
      businessType: 'online',
      businessName: 'Creator Stack',
      title: 'Free Notion Productivity Template Pack',
      description: 'A polished creator dashboard pack with planners, CRM views, and launch trackers.',
      offerText: 'FREE',
      imageUrl: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/creator-stack',
      productUrl: 'https://example.com/creator-stack/notion-pack',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 4 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 205,
      claimCount: 205,
      category: 'Digital',
    },
    {
      id: 'online-seed-17',
      businessType: 'online',
      businessName: 'Render Room',
      title: 'Canva Social Pack Download',
      description: 'A fresh social media pack with reels covers, stories, and promo slides for creators.',
      offerText: 'FREE DOWNLOAD',
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/render-room',
      productUrl: 'https://example.com/render-room/social-pack',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 95 * 60 * 1000,
      expiresAt: now + 10 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 48,
      claimCount: 48,
      category: 'Digital',
    },
    {
      id: 'online-seed-18',
      businessType: 'online',
      businessName: 'Prompt Atlas',
      title: 'AI Workflow Starter Vault',
      description: 'A curated starter set of prompts, templates, and automations for creators and teams.',
      offerText: '$49 → $19',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/prompt-atlas',
      productUrl: 'https://example.com/prompt-atlas/starter-vault',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 21 * 60 * 1000,
      expiresAt: now + 3 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 71,
      claimCount: 71,
      category: 'Digital',
    },
    {
      id: 'online-seed-19',
      businessType: 'online',
      businessName: 'Northern Nest',
      title: 'Linen Bedding Event',
      description: 'Stonewashed sheet sets, pillowcases, and duvet covers are discounted through tonight.',
      offerText: 'UP TO 45% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/northern-nest',
      productUrl: 'https://example.com/northern-nest/linen-event',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 19 * 60 * 1000,
      expiresAt: now + 6 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 59,
      claimCount: 59,
      category: 'Home',
    },
    {
      id: 'online-seed-20',
      businessType: 'online',
      businessName: 'Cozy Circuit',
      title: 'Smart Lamp Duo Bundle',
      description: 'Two app-connected lamps in one discounted lighting bundle for desk and bedside setups.',
      offerText: '$118 → $79',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/cozy-circuit',
      productUrl: 'https://example.com/cozy-circuit/lamp-bundle',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 2 * 60 * 60 * 1000,
      expiresAt: now + 2 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 17,
      claimCount: 17,
      category: 'Home',
    },
    {
      id: 'online-seed-21',
      businessType: 'online',
      businessName: 'Sora Home',
      title: 'Kitchen Organizer Quick Drop',
      description: 'Drawer trays, spice racks, and shelf risers are bundled into one home-organization special.',
      offerText: '3 FOR $24',
      imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/sora-home',
      productUrl: 'https://example.com/sora-home/organizer-drop',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 13 * 60 * 1000,
      expiresAt: now + 70 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 33,
      claimCount: 33,
      category: 'Home',
    },
    {
      id: 'online-seed-22',
      businessType: 'online',
      businessName: 'Daily Perks',
      title: 'Free Shipping Code Drop',
      description: 'A no-minimum shipping code just dropped for one checkout per customer.',
      offerText: 'FREE SHIPPING',
      imageUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/daily-perks',
      productUrl: 'https://example.com/daily-perks/shipping-code',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 3 * 60 * 1000,
      expiresAt: now + 40 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 129,
      claimCount: 129,
      category: 'Freebies',
    },
    {
      id: 'online-seed-23',
      businessType: 'online',
      businessName: 'Sample Society',
      title: 'Free Trial Box Claim',
      description: 'Grab a limited claim on this month’s rotating sample box while inventory lasts.',
      offerText: 'FREE',
      imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/sample-society',
      productUrl: 'https://example.com/sample-society/trial-box',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 55 * 60 * 1000,
      expiresAt: now + 50 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 88,
      claimCount: 88,
      category: 'Freebies',
    },
    {
      id: 'online-seed-24',
      businessType: 'online',
      businessName: 'Font Foundry',
      title: 'Free Font Pairing Pack',
      description: 'A clean set of headline and body font pairings built for modern brand kits.',
      offerText: 'FREE DOWNLOAD',
      imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/font-foundry',
      productUrl: 'https://example.com/font-foundry/free-pack',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 150 * 60 * 1000,
      expiresAt: now + 12 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 36,
      claimCount: 36,
      category: 'Freebies',
    },
    {
      id: 'online-seed-25',
      businessType: 'online',
      businessName: 'Mode Shift',
      title: 'Creator Desk Essentials Sale',
      description: 'Cable docks, mic arms, and desk mats are discounted in one creator-focused online event.',
      offerText: 'SAVE 30%',
      imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/mode-shift',
      productUrl: 'https://example.com/mode-shift/desk-sale',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 36 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000 + 20 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 41,
      claimCount: 41,
      category: 'Tech',
    },
    {
      id: 'online-seed-26',
      businessType: 'online',
      businessName: 'Patch Notes',
      title: 'Streamer Overlay Pack Deal',
      description: 'Animated overlay scenes, alerts, and transitions bundled for live creators.',
      offerText: '60% OFF PACK',
      imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/patch-notes',
      productUrl: 'https://example.com/patch-notes/overlay-pack',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 11 * 60 * 1000,
      expiresAt: now + 85 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 57,
      claimCount: 57,
      category: 'Digital',
    },
    {
      id: 'online-seed-28',
      businessType: 'online',
      businessName: 'Velvet Lane',
      title: 'Evening Dress Edit',
      description: 'A dress edit for weddings, dinners, and events just went live with launch markdowns.',
      offerText: '$120 → $72',
      imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/velvet-lane',
      productUrl: 'https://example.com/velvet-lane/evening-edit',
      hasTimer: false,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 4 * 60 * 60 * 1000,
      expiresAt: now + 4 * 24 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 14,
      claimCount: 14,
      category: 'Fashion',
    },
    {
      id: 'online-seed-29',
      businessType: 'online',
      businessName: 'Open Shelf',
      title: 'Free Recipe eBook & Pantry Planner',
      description: 'Download a recipe bundle plus a pantry planner printable while today’s freebie is live.',
      offerText: 'FREE',
      imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/open-shelf',
      productUrl: 'https://example.com/open-shelf/free-ebook',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 14 * 60 * 1000,
      expiresAt: now + 65 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 91,
      claimCount: 91,
      category: 'Freebies',
    },
    {
      id: 'online-seed-30',
      businessType: 'online',
      businessName: 'Circuit Core',
      title: '4K Monitor Price Crash',
      description: 'Desk setup shoppers are piling into this 27-inch 4K monitor flash markdown.',
      offerText: '$329 → $249',
      imageUrl: 'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://example.com/circuit-core',
      productUrl: 'https://example.com/circuit-core/4k-monitor',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 9 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 133,
      claimCount: 133,
      category: 'Tech',
    },
    {
      id: 'online-seed-31',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Beats Studio Pro Noise-Canceling Headphones',
      description: 'Premium over-ear wireless headphones with personalized spatial audio and all-day battery are on a limited Amazon drop right now.',
      offerText: '18% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
      productUrl: 'https://www.amazon.com/Beats-Studio-Pro-Personalized-Compatibility/dp/B0C8PR4W22?pd_rd_w=HNAte&content-id=amzn1.sym.a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_p=a2aba816-9a6a-4a40-9b91-05f87c414aef&pf_rd_r=ZRGKW3BF3SC8YGHXGY8G&pd_rd_wg=EJ2Z6&pd_rd_r=2f966557-8253-41ba-9298-33dfb786bb66&pd_rd_i=B0C8PR4W22&th=1&linkCode=ll2&tag=livedrop0d-20&linkId=b432954763c206e4eaea2d92e461d095&language=en_US&ref_=as_li_ss_tl',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 12 * 60 * 1000,
      expiresAt: now + 2 * 60 * 60 * 1000 + 15 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 167,
      claimCount: 167,
      category: 'Tech',
    },
    {
      id: 'online-seed-32',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Smart Desk Lamp Deal Drop',
      description: 'A compact LED desk lamp with adjustable brightness and a clean home-office look is moving fast in today’s Amazon event.',
      offerText: 'DEAL',
      imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 22 * 60 * 1000,
      expiresAt: now + 95 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 121,
      claimCount: 121,
      category: 'Home',
    },
    {
      id: 'online-seed-33',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Everyday Sneaker Flash Markdown',
      description: 'Lightweight casual sneakers are part of a quick online apparel markdown with fresh sizes still in stock.',
      offerText: '20% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 8 * 60 * 1000,
      expiresAt: now + 150 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 44,
      claimCount: 44,
      category: 'Fashion',
    },
    {
      id: 'online-seed-35',
      businessType: 'online',
      businessName: 'Amazon',
      title: 'Portable Charger Quick Save',
      description: 'A travel-friendly battery pack with USB-C fast charging is part of a fresh mobile-tech deal drop today.',
      offerText: '25% OFF',
      imageUrl: 'https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=900&q=80',
      websiteUrl: 'https://amzn.to/XXXX',
      productUrl: 'https://amzn.to/XXXX',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: now - 18 * 60 * 1000,
      expiresAt: now + 70 * 60 * 1000,
      maxClaims: 999,
      currentClaims: 152,
      claimCount: 152,
      category: 'Tech',
    },
    {
      id: 'momcozy-kleanpal-pro',
      businessType: 'online',
      businessName: 'Momcozy',
      title: 'Momcozy KleanPal Pro Baby Bottle Washer',
      description: 'All-in-One Cleaning Machine for Bottles, Pump Parts & Baby Essentials - Time-Saving & Effortless Care. Powerful cleaning with steam sterilization and comprehensive drying.',
      offerText: '33% OFF - $239.99',
      imageUrl: 'https://m.media-amazon.com/images/I/51bYxBVtzSL._SY355_.jpg',
      affiliateUrl: 'https://amzn.to/4bNgyoT',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4bNgyoT',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 5 * 60 * 1000,
      expiresAt: now + 24 * 60 * 60 * 1000,
      maxClaims: 50,
      currentClaims: 12,
      claimCount: 12,
      category: 'Home',
    },
    {
      id: 'samsung-watch-band-ynitec',
      businessType: 'online',
      businessName: 'Ynitec',
      title: 'Sport Bands Compatible with Samsung Galaxy Watch 7 6 5 4 Band 40mm 44mm',
      description: 'No Gap Soft Silicone Strap for Smart Watch S 7 6 5 4 FE, 20mm Wristbands for GalaxyWatch. Features gapless connection technology, durable stainless steel buckle, breathable and sweat-resistant material.',
      offerText: '$5.99 (30% OFF)',
      imageUrl: 'https://m.media-amazon.com/images/I/61Z09Ia2gOL._AC_SY395_.jpg',
      affiliateUrl: 'https://amzn.to/4bOaJYr',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4bOaJYr',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 2 * 60 * 1000,
      expiresAt: now + 12 * 60 * 60 * 1000,
      maxClaims: 100,
      currentClaims: 87,
      claimCount: 87,
      category: 'Tech',
    },
    {
      id: 'purecozy-checkered-rug',
      businessType: 'online',
      businessName: 'PureCozy',
      title: 'Checkered Runner Rug 2x6 for Bedroom, Brown Modern Shag Rug Super Soft Long Carpet Washable Fluffy Rugs for Living Room Bedside Sofa Home Dorm Decor Aesthetic',
      description: 'Plush Modern Rug: PureCozy fuzzy rug has a long and plush pile, creating a cozy and luxurious feel for your home. Perfect for modern home decor, it blends seamlessly into living rooms, bedrooms. Eco-friendly packaging, rug may look flat at first—just lay it flat for 48h to regain its full thickness and fluffiness.',
      offerText: '$14.39 (30% OFF)',
      imageUrl: 'https://m.media-amazon.com/images/I/81SEI2WN9pL._AC_SY450_.jpg',
      affiliateUrl: 'https://amzn.to/4t0cxnS',
      websiteUrl: 'https://www.amazon.com',
      productUrl: 'https://amzn.to/4t0cxnS',
      hasTimer: true,
      distance: 'Online',
      lat: 0,
      lng: 0,
      createdAt: Date.now() - 1 * 60 * 1000,
      expiresAt: now + 24 * 60 * 60 * 1000,
      maxClaims: 50,
      currentClaims: 5,
      claimCount: 5,
      category: 'Home',
    },
  ];
}

/**
 * Helper to calculate a lat/lng offset based on miles.
 * This is a rough approximation for demo purposes.
 * 1 degree lat is ~69 miles.
 * 1 degree lng is ~69 * cos(lat) miles.
 */
function getOffsetLocation(center: UserLocation, miles: number): { lat: number; lng: number } {
  const latOffset = (miles / 69) * (Math.random() > 0.5 ? 1 : -1) * (0.7 + Math.random() * 0.3);
  const lngOffset = (miles / (69 * Math.cos(center.lat * Math.PI / 180))) * (Math.random() > 0.5 ? 1 : -1) * (0.7 + Math.random() * 0.3);
  
  return {
    lat: center.lat + latOffset,
    lng: center.lng + lngOffset
  };
}

